# Generated by Django 4.1.7 on 2023-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACNum', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcaNum', models.CharField(max_length=10)),
                ('razaoSocial', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('cpfcnpj', models.CharField(max_length=15)),
            ],
        ),
    ]
